New-ADAuthenticationPolicy -Name "Policy-DHCP-Users" -Description "Politique pour Admin-DHCP et User-DHCP"
New-ADAuthenticationPolicy -Name "Policy-DNS-Users" -Description "Politique pour Admin-DNS et User-DNS"
New-ADAuthenticationPolicy -Name "Policy-VPN-Users" -Description "Politique pour Admin-VPN et User-VPN"
New-ADAuthenticationPolicy -Name "Policy-RDP-Users" -Description "Politique pour Admin-RDP et User-RDP"
New-ADAuthenticationPolicy -Name "Policy-Fichiers-Home-Users" -Description "Politique pour Admin-Fichiers-Home et User-Fichiers-Home"
New-ADAuthenticationPolicy -Name "Policy-Fichiers-Partages-Users" -Description "Politique pour Admin-Fichiers-Partages et User-Fichiers-Partages"
New-ADAuthenticationPolicy -Name "Policy-Bastion-Users" -Description "Politique pour Admin-Bastion et User-Bastion"
New-ADAuthenticationPolicy -Name "Policy-Reseau-Users" -Description "Politique pour User-Reseau"
New-ADAuthenticationPolicy -Name "Policy-Systeme-Users" -Description "Politique pour User-Systeme"